In [1]:
from bs4 import BeautifulSoup
import urllib2, requests
import pandas as pd
from sklearn.linear_model import LogisticRegression
import re
from sklearn import linear_model, preprocessing, cross_validation, metrics, pipeline

In [2]:
% matplotlib inline
from os import path
from wordcloud import WordCloud
import matplotlib.pyplot as plt

#d = path.dirname(__file__)

trump = open('speeches.txt').read()
hillary = open('hillary_clinton.txt').read()
#text
#wordcloud = WordCloud(max_font_size=40, relative_scaling=.5).generate(text)
#plt.figure()
#plt.imshow(wordcloud)
#plt.axis("off")
#plt.show()

In [3]:
#trump = re.sub(r'\W+',' ', trump)
#hillary = re.sub(r'\W+',' ', hillary)

In [4]:
type(trump)

str

In [5]:
trump_sentence = trump.replace('\n','').replace('\r','').split('.')
hillary_sentence = hillary.replace('\n','').replace('\r','').split('.')

In [6]:
len(trump_sentence)

18216

In [7]:
len(hillary_sentence)

14832

In [8]:
n = 10
trump_list = [''.join(trump_sentence[i:i+n]) for i in range(0, len(trump_sentence), n)]
hillary_list = [''.join(hillary_sentence[i:i+n]) for i in range(0, len(hillary_sentence), n)]

In [9]:
trump_list = [re.sub(r'\W+',' ', trump_list[i]) for i in range(len(trump_list))]
hillary_list = [re.sub(r'\W+',' ', hillary_list[i]) for i in range(len(hillary_list))]

In [10]:
len(trump_list)

1822

In [11]:
len(hillary_list)

1484

In [12]:
#len(re.findall(r'\w+', hillary))

In [13]:
df = pd.DataFrame(trump_list)

In [14]:
df.columns = ['speech']
df['is_Trump'] = 1

In [15]:
df_hill = pd.DataFrame(hillary_list)
df_hill.columns = ['speech']
df_hill['is_Trump'] = 0

In [16]:
df = pd.concat([df,df_hill])

In [17]:
#import re
#line = " I am having a very nice day."
#count = len(re.findall(r'\w+', text))

NameError: name 'text' is not defined

In [83]:
X = df['speech']
y = df['is_Trump']

In [75]:
X.shape

(3306, 1)

In [76]:
y.shape

(3306,)

In [71]:
len(X)

3306

In [72]:
len(y)

3306

In [59]:
type(X)

pandas.core.frame.DataFrame

In [60]:
X

speech
0     Thank you so much That s so nice Isn t he a gr...
1      They have something in common Hard working pe...
2      Very simple Politicians are all talk no actio...
3      A total catastrophe and by the way it really ...
4      They re all over the place But for 10 okay No...
5      It s a big fat horrible lie Your deductibles ...
6      I build I build nice fences but I build great...
7      You can certainly have terrorists You can cer...
8     IRS e mails I get sued all the time okay I run...
9      He never did a deal He did one deal A house A...
10     But they talk about it And then you have a pr...
11     I mean I ve made so much money fighting again...
12     I never thought that they d have the guts to ...
13     Be very careful Because we re just going to l...
14     They don t even respect us they don t even ca...
15     I mean I walk down the streets of New York an...
16     And like I like Congressman Ryan I like a lot...
17     We re fighting people that want to overturn S...
18     The power And we have to be in a position whe...
19     They re taking it out Trillion of dollars and...
20     I go to China They are building a bridge on e...
21     So you have a white terraza floor and they pu...
22     The ones that sort of go like this demonstrat...
23     We are just in such serious trouble because w...
24     Why aren t they doing something to justify wh...
25     What do you think they re going to say oh we ...
26     Most people are like that I mean most people ...
27     But I said it I was the one that said it firs...
28     I was never a big fan but his brother gave us...
29     It s so simpleSo just in summing up and I jus...
...                                                 ...
1454   I ll press our partners in the region to prev...
1455   Our quarrel is not and never has been with th...
1456  I will push for renewed diplomacy to solve the...
1457   And on every front we need to keep working cl...
1458   I know that my saying This deal makes you saf...
1459   It is personal As president I m committed to ...
1460   Like my friend Chuck Schumer who s going to b...
1461   Let s resist denigrating the patriotism or lo...
1462   There s a lot that Democrats and Republicans ...
1463   No country comes close to matching our advant...
1464   I want to recognize former Congressman Joe Ga...
1465   And the choices we make will have lasting con...
1466  I wish every Cuban back in Cuba could spend a ...
1467   I well remember what happened to previous att...
1468  So in 2009 we tried something new The Obama ad...
1469   Slowly Cubans were getting a taste of a diffe...
1470  The future for Cuba is not foreordained But th...
1471   The Cuba embargo needs to go once and for all...
1472   In fact there may be no stronger argument for...
1473   An American embassy in Havana isn t a concess...
1474   If Congress won t act to do this I would use ...
1475   Bloggers The more relationships we build the ...
1476   We want more American airplanes and ferries a...
1477   Let him try to put up barriers to American te...
1478   We were isolated in our opposition to opening...
1479   Latin America is now home to vibrant democrac...
1480   And if we don t make no mistake others will C...
1481  Slowly but surely we also repaired America s t...
1482   I believe the future holds far more opportuni...
1483                       Thank you all very very much

[3306 rows x 1 columns]

In [61]:
from sklearn import feature_extraction

In [62]:
cout_vect = feature_extraction.text.CountVectorizer(lowercase=True)

In [63]:
X_vect = cout_vect.fit_transform(X)
X_vect

<1x1 sparse matrix of type '<type 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [64]:
dense = X_vect.todense()

In [65]:
logreg = LogisticRegression(random_state=77)
logreg.fit(X_vect, y)
#Y_pred = logreg.predict(X_test)

ValueError: Found arrays with inconsistent numbers of samples: [   1 3306]

In [66]:
logreg.score(X=X_vect, y=y)

NotFittedError: This LogisticRegression instance is not fitted yet

In [40]:
cross_validation.cross_val_score(linear_model.LogisticRegression(), X=X_vect, y=y, cv=5)

array([ 0.94712991,  0.92296073,  0.99092284,  0.98487141,  0.97121212])

In [91]:
#temp_str = "Homicides last year increased by 17 percent in America\’s 50 largest cities. That\’s the largest increase in 25 years. In our nation\’s capital, killings have risen by 50 percent. They are up nearly 60 percent in nearby Baltimore."
#temp_str = "If Trump wants to talk about debt, let’s start with the $34 trillion (that's a \"t\") his tax plan would run up."
#temp_str = "Congratulations to my children, Don and Tiffany, on having done a fantastic job last night. I am very proud of you!"
#temp_str = "You know, over the past few months, I have had the opportunity to listen to Americans’ concerns about an economy that still isn’t delivering for them. It’s not delivering the way that it should. It still seems, to most Americans that I have spoken with, that it is stacked for those at the top."
#temp_str =  "It is also a coming together, much the way women come together every day in every country. We come together in fields and factories, in village markets and supermarkets, in living rooms and board rooms. Whether it is while playing with our children in the park, or washing clothes in a river, or taking a break at the office water cooler, we come together and talk about our aspirations and concern. And time and again, our talk turns to our children and our families. However different we may appear, there is far more that unites us than divides us. We share a common future, and we are here to find common ground so that we may help bring new dignity and respect to women and girls all over the world, and in so doing bring new strength and stability to families as well."
temp_str1 =  "All I do is hug Democrats. It gets me in trouble all the time. All the time,"
temp_str2 =  "President Roosevelt called on every American to do his or her part, and every American answered. He said there’s no mystery about what it takes to build a strong and prosperous America: “Equality of opportunity… Jobs for those who can work… Security for those who need it… The ending of special privilege for the few… The preservation of civil liberties for all… a wider and constantly rising standard of living."
temp_str = []
#temp_str1 = temp_str1.replace('\n','').replace('\r','')
temp_str2 = temp_str2.replace('\n','').replace('\r','')
#temp_str.append(temp_str1)
temp_str.append(temp_str2)
X_pred_temp = pd.DataFrame(temp_str, columns=['speech'])


X_pred = cout_vect.transform(X_pred_temp)

In [42]:
temp_str

['All I do is hug Democrats. It gets me in trouble all the time. All the time,',
 'President Roosevelt called on every American to do his or her part, and every American answered. He said there\xe2\x80\x99s no mystery about what it takes to build a strong and prosperous America: \xe2\x80\x9cEquality of opportunity\xe2\x80\xa6 Jobs for those who can work\xe2\x80\xa6 Security for those who need it\xe2\x80\xa6 The ending of special privilege for the few\xe2\x80\xa6 The preservation of civil liberties for all\xe2\x80\xa6 a wider and constantly rising standard of living.']

In [92]:
X_pred_temp

speech
0  President Roosevelt called on every American t...

In [44]:
#X_series = pd.concat([X_series,X])
#X_pred = cout_vect.fit_transform(X_series)

In [45]:

X_pred

<1x16786 sparse matrix of type '<type 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [46]:
logreg.predict(X_pred)

array([1])

In [35]:
import numpy as np
np.sum(X_pred.todense())

1

In [93]:
X_pred_temp['speech']

0    President Roosevelt called on every American t...
Name: speech, dtype: object

In [84]:
estimator = pipeline.Pipeline(steps=[('countVec', feature_extraction.text.CountVectorizer(lowercase=True)),
                                    ('reg',LogisticRegression())
                                    ])


In [85]:
y.shape

(3306,)

In [86]:
estimator = estimator.fit(X=X, y=y)

In [87]:
estimator.score(X=X, y=y)

0.999697519661222

In [94]:
estimator.predict(X_pred_temp['speech'])

array([0])