In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import metrics
import string

In [2]:
true_coef = [1, 2, -3, 4, 50]
def true(x):    
    return np.dot(true_coef, x) 

In [3]:
N = 100
X = pd.DataFrame([np.random.uniform(-1,1, len(true_coef)) for _ in range(N)], columns=list(string.lowercase[:len(true_coef)]))
y = true(X.T) + np.random.normal(0, 100)

In [4]:
lm = linear_model.LinearRegression()
lm.fit(X, y)
print lm.coef_
y_pred = lm.predict(X)
print metrics.mean_squared_error(y, y_pred)

[  1.   2.  -3.   4.  50.]
6.04330562272e-28


In [5]:
# change column e to be correlated with column b
X.e = X.b + np.random.normal(0, 1000)

# recompute y
y = true(X.T) + np.random.normal(0, 100)

# check correlation
X.corr()

a         b         c         d         e
a  1.000000 -0.126811 -0.032686 -0.048629 -0.126811
b -0.126811  1.000000 -0.027135  0.050752  1.000000
c -0.032686 -0.027135  1.000000  0.033842 -0.027135
d -0.048629  0.050752  0.033842  1.000000  0.050752
e -0.126811  1.000000 -0.027135  0.050752  1.000000

In [11]:
# fit a linear regression model and check coefficients 
lm = linear_model.LinearRegression()
lm.fit(X,y)
print lm.coef_
y_pred = lm.predict(X)
print metrics.mean_squared_error(y, y_pred)

[  1.           9.60207744  -3.           4.          42.39792256]
9.52912065661e-24


In [13]:
# fit a ridge regression model and check coefficients
rlm = linear_model.Ridge(alpha=1.0)

rlm.fit(X,y)
print rlm.coef_
y_pred = rlm.predict(X)
print metrics.mean_squared_error(y, y_pred)

[  0.86815199  25.63348286  -2.92093523   3.91155888  25.63348286]
0.194815714899


In [14]:
# fit a lasso regression model and check coefficients
lm = linear_model.Lasso(alpha=1.0)

lm.fit(X,y)
print lm.coef_
y_pred = lm.predict(X)
print metrics.mean_squared_error(y, y_pred)

[  0.          49.28048494  -0.           0.97649101   0.        ]
8.4845059307


In [9]:
# fit a elastic net regression model and check coefficients

In [16]:
lm = linear_model.ElasticNet(alpha=1.0, l1_ratio = 0.5)

lm.fit(X,y)
print lm.coef_
y_pred = lm.predict(X)
print metrics.mean_squared_error(y, y_pred)

[ -0.17516248  14.84019202  -0.67786738   1.40565755  14.83997911]
181.150931129
