In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing, feature_extraction

In [2]:
df = pd.DataFrame({'car':np.random.choice(['BMW', 'Mini', 'Mercedes'], size=10, replace=True)}, dtype='category')

In [3]:
df['car'].head()

0         BMW
1    Mercedes
2    Mercedes
3        Mini
4        Mini
Name: car, dtype: category
Categories (3, object): [BMW, Mercedes, Mini]

In [4]:
list(df.car.cat.codes)

[0, 1, 1, 2, 2, 2, 2, 1, 1, 1]

In [5]:
preprocessing.OneHotEncoder(sparse=False).fit_transform([[1],[2],[3],[1],[2],[3]])
#preprocessing.OneHotEncoder(sparse=False).fit_transform([1,2,3,1,2,3])

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [6]:
ohe = preprocessing.OneHotEncoder(sparse=False)

In [7]:
# ohe.fit_transform([[cod] for cod in df.car.cat.codes])
ohe.fit_transform(df.car.cat.codes.reshape(-1,1))

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.]])

In [8]:
df.car

0         BMW
1    Mercedes
2    Mercedes
3        Mini
4        Mini
5        Mini
6        Mini
7    Mercedes
8    Mercedes
9    Mercedes
Name: car, dtype: category
Categories (3, object): [BMW, Mercedes, Mini]

In [9]:
pd.Categorical(df.car, categories=['BMW', 'Mini'])

[BMW, NaN, NaN, Mini, Mini, Mini, Mini, NaN, NaN, NaN]
Categories (2, object): [BMW, Mini]

In [10]:
class OneHotEncoderPandasCategoricalSeries():
    def __init__(self, sparse=False, **kwargs):
        self.ohe = preprocessing.OneHotEncoder(handle_unknown='ignore', sparse=sparse, **kwargs)

    def _X_for_onehotenc(self, X):
        return X.cat.codes.reshape(-1,1 )
        # return [[x] for x in X.cat.codes]
    
    def fit(self, X, y=None):        
        self.categories = X.cat.categories
        self.ohe.fit(self._X_for_onehotenc(X))
        return self
        
        
    def transform(self, X, y=None):
        if np.all(X.cat.categories != self.categories):
            X = pd.Categorical(X, categories=self.categories)
        return self.ohe.transform(self._X_for_onehotenc(X))
        

In [21]:
ohec = OneHotEncoderPandasCategoricalSeries()

In [23]:
ohec.fit(df.car)

<__main__.OneHotEncoderPandasCategoricalSeries instance at 0x7fe921b97d40>

In [17]:
df = pd.DataFrame({'car':np.random.choice(['BMW', 'Mini', 'Mercedes'], size=10, replace=True)}, dtype='category')

In [19]:
df.car

0         BMW
1         BMW
2        Mini
3         BMW
4        Mini
5         BMW
6    Mercedes
7         BMW
8        Mini
9        Mini
Name: car, dtype: category
Categories (3, object): [BMW, Mercedes, Mini]

In [24]:
ohec.transform(df.car)

array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.]])

In [14]:
df2 = pd.DataFrame({'car':np.random.choice(['BMW', 'Mini', 'Mercedes','Ferrari'], size=10, replace=True)}, dtype='category')

In [15]:
df2

car
0  Mercedes
1      Mini
2   Ferrari
3   Ferrari
4   Ferrari
5       BMW
6      Mini
7      Mini
8       BMW
9  Mercedes

In [16]:
ohec.transform(df2.car)

ValueError: Lengths must match to compare