---
title: Pipelines and custom transfomers in SKLearn
duration: "1:25"
creator:
    name: Francesco Mosconi
    city: SF
---

# ![](https://ga-dash.s3.amazonaws.com/production/assets/logo-9f88ae6c9c3871690e33280fcf557f33.png) Pipelines and custom transfomers in SKLearn
Week 5 | Lesson 2.2

### LEARNING OBJECTIVES
*After this lesson, you will be able to:*
- create pipelines for cleaning and manipulating data
- use pipelines to preprocess data from the SQL database
- use pipeline in combination with classification
- create a custom transformer using the `TransformerMixin` class

### STUDENT PRE-WORK
*Before this lesson, you should already be able to:*
- extract data from a database
- perform classification

### INSTRUCTOR PREP
*Before this lesson, instructors will need to:*
- Read in / Review any dataset(s) & starter/solution code
- Generate a brief slide deck
- Prepare any specific materials
- Provide students with additional resources

### LESSON GUIDE

| TIMING  | TYPE  | TOPIC  |
|:-:|---|---|
| 5 mins | [Opening](#opening) | Opening |
| 10 mins | [Introduction](#introduction) | Data Pipelines |
| 25 mins | [Demo](#demo) | Pipelines in scikit-learn |
| 15 mins | [Guided-practice](#guided-practice) | Make Pipeline and the preprocessing module |
| 10 minutes | [Demo](#demo_2) | Custom Transformers |
| 20 minutes | [Ind-practice](#ind-practice) | Putting it all together |
| 5 mins | [Conclusion](#conclusion) | Conclusion |


<a name="opening"></a>
## Opening (5 mins)
Many organizations rely on data engineering teams to encode these common tasks into pipelines. **Data pipelines** are a series of automated data transformations that ensure the validity of your work for routine data maintenance tasks. 

<a name="introduction"></a>
## Data Pipelines (10 mins)

The term _Pipeline_ is used to indicate a series of concatenated data transformations. Each stage of the pipeline feeds from the previous stage, i.e. the output of a stage is plugged into the input of the next stage and data flows through the pipeline from beginning to end as water flows through... a pipeline.

![Pipeline](./assets/images/pipeline.png)

Each processing stage has an input, where data comes in, and an output, where processed data comes out.

**Check:** Ask the students to give some examples of data transformations.

Pipelines provide a higher level of abstraction than the individual building blocks.

<a name="demo"></a>
## Pipelines in scikit-learn (25 mins)
One way to improve coding and model management is to use pipelines in `scikit-learn`. These tie together all the steps that you may need to prepare your dataset and make your predictions. Because you will need to perform all of the exact same transformations on your evaluation data, encoding the exact steps is important.

In [1]:
from sklearn import pipeline

To show how a pipeline works, we'll use an example involving Natural Language Processing. Data comes from the [Evergreen Stumbleupon Kaggle Competition](https://www.kaggle.com/c/stumbleupon/data), where participants where challenged to build a classifier to categorize webpages as evergreen or non-evergreen. Binary evergreen labels (either evergreen (1) or non-evergreen (0)) were provided. We'll focus on the page title text.

In [2]:
import pandas as pd
import json

data = pd.read_csv("./datasets/stumbleupon.tsv", sep='\t')
data['title'] = data.boilerplate.map(lambda x: json.loads(x).get('title', ''))
data['body'] = data.boilerplate.map(lambda x: json.loads(x).get('body', ''))

titles = data['title'].fillna('')
titles[0:3]

0    IBM Sees Holographic Calls Air Breathing Batte...
1    The Fully Electronic Futuristic Starting Gun T...
2    Fruits that Fight the Flu fruits that fight th...
Name: title, dtype: object

In [3]:
y = data['label']
y[0:3]

0    0
1    1
2    1
Name: label, dtype: int64

In [4]:
y.value_counts() / len(y)

1    0.51332
0    0.48668
Name: label, dtype: float64

Each datapoint is a string of free form text. How can we feed this to a model? The simplest way is to build a dictionary of words and use those as features. This is what a `CountVectorizer` does.

Example:


|Sentence|the|cat|is|on|table|blue|
|---|---|---|---|---|---|---|
|The cat is on the table|2|1|1|1|1|0|
|The table is blue|1|0|1|0|1|1|
|...||||||

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(max_features = 1000,
                             ngram_range=(1, 2),
                             stop_words='english', 
                             min_df=1,
                             max_df=0.9,
                             binary=True)

vectorizer.fit(['IBM Sees the Holographic Calls Air Breathing Holographic', 'This is the second document hot air'])

CountVectorizer(analyzer=u'word', binary=True, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=0.9, max_features=1000, min_df=1,
        ngram_range=(1, 2), preprocessor=None, stop_words='english',
        strip_accents=None, token_pattern=u'(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [6]:
vectorizer.get_feature_names()

[u'air breathing',
 u'breathing',
 u'breathing holographic',
 u'calls',
 u'calls air',
 u'document',
 u'document hot',
 u'holographic',
 u'holographic calls',
 u'hot',
 u'hot air',
 u'ibm',
 u'ibm sees',
 u'second',
 u'second document',
 u'sees',
 u'sees holographic']

In [7]:
vectorizer.transform(['IBM Sees Holographic Air']).todense()

matrix([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1]])

In [8]:
pd.DataFrame(vectorizer.transform(['IBM Sees Holographic Air',
                                   'This is a test', 
                                   "IBM is just pure hot air air"]).todense(), 
             columns=vectorizer.get_feature_names())

air breathing  breathing  breathing holographic  calls  calls air  \
0              0          0                      0      0          0   
1              0          0                      0      0          0   
2              0          0                      0      0          0   

   document  document hot  holographic  holographic calls  hot  hot air  ibm  \
0         0             0            1                  0    0        0    1   
1         0             0            0                  0    0        0    0   
2         0             0            0                  0    1        1    1   

   ibm sees  second  second document  sees  sees holographic  
0         1       0                0     1                 1  
1         0       0                0     0                 0  
2         0       0                0     0                 0

**Check**: What is the meaning of the various parameters used at initialization of the Vectorizer?


Let's use the vectorizer to fit all the titles and build a feature matrix.

In [9]:
# Use `fit` to learn the vocabulary of the titles
vectorizer.fit(titles)

# Use `tranform` to generate the sample X word matrix - one column per feature (word or n-grams)
X = vectorizer.transform(titles)

# X = vectorizer.fit_transform(titles)

We used this input X, a matrix of all common n-grams in the dataset, as an input to our classifier. We wanted to classify how evergreen a story was, based on these inputs.


In [10]:
from sklearn import linear_model, cross_validation

model = linear_model.LogisticRegression()
scores = cross_validation.cross_val_score(model, X, y)

print('CV scores: {}'.format(scores))

print('Average CVScore: {:0.3f} +/- {:0.3f}'.format(scores.mean(), scores.std()))

CV scores: [ 0.74574209  0.75659229  0.75487013]
Average CVScore: 0.752 +/- 0.005


#### Combining Steps in Pipelines

Often we will want to combine these steps to evaluate some future dataset. Therefore, we need to make sure we perform the _exact same_ transformations on the data. If "has_brownies_in_text" is column 19, we need to make sure it is __also__ column 19 during future evaluation.

Pipelines combines both pre-processing and model building steps into a _single object_. Rather than manually evaluating the transformers and then feeding them into the models, pipelines ties both of these steps together.

Similar to models and vectorizers in scikit-learn, pipelines are equipped with `fit` and `predict` or `predict_proba` methods (as any model would be), but they ensure that proper data transformations are performed.

In [11]:
# Split the data into a training set
training_data = data[:6000]
X_train = training_data['title'].fillna('')
y_train = training_data['label']

# These rows are rows obtained in the future, unavailable at training time
X_new = data[6000:]['title'].fillna('')

pipe = pipeline.Pipeline([
        ('vec', vectorizer),
        ('model', model)   
    ])

# Fit the full pipeline
# This means we perform the steps laid out above
# First we fit the vectorizer,
# And then feed the output of that into the fit function of the model

pipe.fit(X_train, y_train)

# Here again we apply the full pipeline for predictions
# The text is transformed automatically to match the features from the pipeline
pipe.predict_proba(X_new)

array([[ 0.46801259,  0.53198741],
       [ 0.28316885,  0.71683115],
       [ 0.00513415,  0.99486585],
       ..., 
       [ 0.2906378 ,  0.7093622 ],
       [ 0.60684131,  0.39315869],
       [ 0.66320386,  0.33679614]])

**Check** Add a `MaxAbsScaler` scaling step to the pipeline, which should occur after the vectorization.

#### Merging Feature Sets in Pipelines

Additionally, we want to merge many different feature sets automatically. Here we can use scikit-learn's `FeatureUnion`.

While scikit-learn pipelines help with managing the transformation from raw data, there may be many steps before this takes place in your pipeline. These pipelines are often referred to as _ETL pipelines_ for "Extract, Transform, Load.""

In an _ETL pipeline_, the data is pulled or extracted from some source (like a database), transformed or manipulated, and then "loaded" into whatever system or analysis requires them.

Many data science teams rely on software tools to manage these ETL pipelines. If a transformation step fails, these tools alert you, or ensure that step can be re-run. If these transformation steps need to happen daily or weekly, these tools can manage that timeline.

- One of the most popular Python tools for this is [Luigi](https://github.com/spotify/luigi) developed by Spotify.
- An alternative is [Airflow](https://github.com/airbnb/airflow) by AirBnB.

<a name="guided-practice"></a>
## Make Pipeline and the preprocessing module (15 mins)

#### make_pipeline
Scikit-learn pipelines can also be built using the `make_pipeline` command.

In [12]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

pipe1 = pipeline.make_pipeline(StandardScaler(), LogisticRegression())    

pipe2 = pipeline.Pipeline(steps=[('standardscaler',StandardScaler()),
                                 ('logisticregression',LogisticRegression())
                                ])

In [13]:
pipe1

Pipeline(steps=[('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('logisticregression', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False))])

In [14]:
pipe2

Pipeline(steps=[('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('logisticregression', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False))])

The two pipelines created above are identical.

### Preprocessing in sklearn (in pairs)

The preprocessing module comes loaded with many very useful pre-processing classes.

**Check** in pairs, assign one function to each pair, they have to read about it in the doc and then explain it to the class.


Data Manipulators
- Binarizer
- KernelCenterer
- MaxAbsScaler
- MinMaxScaler
- Normalizer
- OneHotEncoder
- PolynomialFeatures
- RobustScaler
- StandardScaler

Data Imputation
- Imputer

Function Transformer
- FunctionTransformer

Label Manipulators
- LabelBinarizer
- LabelEncoder
- MultiLabelBinarizer

<a name="demo_2"></a>
## Custom Transformers (10 minutes)

We can implement custom transformers by extending the BaseClass in Scikit-Learn.

In [15]:
from sklearn.base import BaseEstimator, TransformerMixin
import numpy as np

class FeatureMultiplier(BaseEstimator, TransformerMixin):
    def __init__(self, factor):
        self.factor = factor

    def fit(self, X):
        return self

    def transform(self, X, y=None):
        return X * self.factor
    

fm = FeatureMultiplier(2.5)

test = np.diag((1,2,3,4))
print test

# print fm.transform(test)
print fm.fit_transform(test)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[  2.5   0.    0.    0. ]
 [  0.    5.    0.    0. ]
 [  0.    0.    7.5   0. ]
 [  0.    0.    0.   10. ]]


**Check** Compare this with the `FunctionTransformer` from the preprocessing module.

In [16]:
from sklearn import preprocessing

ft = preprocessing.FunctionTransformer(lambda x: x*2.5)

ft.fit_transform(test)

array([[  2.5,   0. ,   0. ,   0. ],
       [  0. ,   5. ,   0. ,   0. ],
       [  0. ,   0. ,   7.5,   0. ],
       [  0. ,   0. ,   0. ,  10. ]])

**Check** Implement a custom transformer that selects a specific feature from a Pandas dataframe. It should be initialized with the column name or the column index and it should return the selected column when transforming a dataframe.

In [17]:
print data.columns

Index([u'url', u'urlid', u'boilerplate', u'alchemy_category',
       u'alchemy_category_score', u'avglinksize', u'commonlinkratio_1',
       u'commonlinkratio_2', u'commonlinkratio_3', u'commonlinkratio_4',
       u'compression_ratio', u'embed_ratio', u'framebased', u'frameTagRatio',
       u'hasDomainLink', u'html_ratio', u'image_ratio', u'is_news',
       u'lengthyLinkDomain', u'linkwordscore', u'news_front_page',
       u'non_markup_alphanum_characters', u'numberOfLinks', u'numwords_in_url',
       u'parametrizedLinkRatio', u'spelling_errors_ratio', u'label', u'title',
       u'body'],
      dtype='object')


In [18]:

class SelectTransformer(BaseEstimator, TransformerMixin):
    def __init__(self, columns):
        self.columns = columns

    def fit(self, X, y=None):
        return self

    def transform(self, X, y=None):
        #return X.ix[:, self.column]
        return X[self.columns]
    
    # def fit_transform(self, X, y=None):
    #     print "Jacques stop doing that! Don't overwrite me!!!"                
    #     return self.fit(X, y).transform(X, y)    
    
st = SelectTransformer(['linkwordscore'])
st.fit_transform(data).head()

# ft = preprocessing.FunctionTransformer(lambda x: x[['urlid','numberOfLinks']])

linkwordscore
0             24
1             40
2             55
3             24
4             14

# Make Union example

In [19]:
class SelectOneColumn(BaseEstimator, TransformerMixin):
    def __init__(self, column):
        self.column = column

    def fit(self, X, y=None):
        return self

    def transform(self, X, y=None):
        # return X.ix[:, self.column]
        return X[self.column]
    
class TextImputter(BaseEstimator, TransformerMixin):
    def __init__(self, input_with = ''):
        self.input_with = input_with

    def fit(self, X, y=None):
        return self

    def transform(self, X, y=None):
        def replace_with(x):
            return x if x is not None else self.input_with            

        return X.apply(replace_with)

class PrintShape(BaseEstimator, TransformerMixin):
    def __init__(self, pre_str = ''):
        self.pre_str = pre_str
    def fit(self, X, y=None):
        return self

    def transform(self, X, y=None):
        print "{}: {}".format(self.pre_str, X.shape)
        return X
    
    
pipeTxt = pipeline.make_pipeline(SelectOneColumn('title'), PrintShape('After Title'),
                                 TextImputter(), PrintShape('After TextImputter'),
                                 CountVectorizer(), PrintShape('After CountVectorizer'))
pipeTxt.fit_transform(data)

After Title: (7395,)
After TextImputter: (7395,)
After CountVectorizer: (7395, 10557)


<7395x10557 sparse matrix of type '<type 'numpy.int64'>'
	with 51034 stored elements in Compressed Sparse Row format>

In [20]:
pipeNum1 = pipeline.make_pipeline(SelectTransformer(['numberOfLinks']), preprocessing.MinMaxScaler())
pipeNum2 = pipeline.make_pipeline(SelectTransformer(['linkwordscore']), preprocessing.Normalizer())

featunion = pipeline.make_union(pipeNum1, pipeNum2, pipeTxt)
new_data = featunion.fit_transform(data)
print "Shape of after Union:", new_data.shape


#pipeline.make_pipeline(featunion, linear_model.LogisticRegression())
#pipeTxt.fit_transform(data)

After Title: (7395,)
After TextImputter: (7395,)


/Users/pizzato/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the normalize function.
  warnings.warn(msg, DataConversionWarning)


After CountVectorizer: (7395, 10557)
Shape of after Union: (7395, 10559)


<a name="ind-practice"></a>
## Putting it all together (20 minutes)

**Check** Revisit the dataset of lab 1.4. How could you use `make_pipeline` and `make_union` to build a pipeline that performs the same steps all in one pass?



<a name="conclusion"></a>
## Conclusion (5 mins)
We have learnt how to use the `Pipeline` construct in order to chain several instructions in one single class. This enables to treat data-processing from a more abstract and more powerful perspective, and it's a pre-cursor to the work we will do when working with Big Data technologies.

***
### ADDITIONAL RESOURCES

- [Pipelines and Feature Union](http://scikit-learn.org/stable/modules/pipeline.html)
- [Example with complex pipeline](http://scikit-learn.org/stable/auto_examples/hetero_feature_union.html#example-hetero-feature-union-py)