In [11]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import metrics
import string

In [12]:
true_coef = [1, 2, -3, 4, 50]
def true(x):    
    return np.dot(true_coef, x) 

In [13]:
N = 100
X = pd.DataFrame([np.random.uniform(-1,1, len(true_coef)) for _ in range(N)], columns=list(string.lowercase[:len(true_coef)]))
y = true(X.T) + np.random.normal(0, 100)


In [14]:
lm = linear_model.LinearRegression()
lm.fit(X, y)
print lm.coef_
# print "R^2", lm.score(X, y)
y_pred = lm.predict(X)
print metrics.mean_squared_error(y, y_pred)

[  1.   2.  -3.   4.  50.]
4.64986171973e-28


In [15]:
X.e = X.b + np.random.normal(0, 100)
y = true(X.T) + np.random.normal(0, 100)

In [16]:
lm = linear_model.LinearRegression()
lm.fit(X, y)
print lm.coef_
# print "R^2", lm.score(X, y)
y_pred = lm.predict(X)
print metrics.mean_squared_error(y, y_pred)

[  1.          83.79016092  -3.           4.         -31.79016092]
3.29579775314e-26


In [17]:
lm = linear_model.Ridge(alpha=0.3)
lm.fit(X, y)
print lm.coef_
# print "R^2", lm.score(X, y)
y_pred = lm.predict(X)
print metrics.mean_squared_error(y, y_pred)

[  0.97373259  25.86229159  -2.98715707   3.96046697  25.86229159]
0.0220302616949


In [20]:
lm = linear_model.Lasso(alpha=0.4)
lm.fit(X, y)
print lm.coef_
# print "R^2", lm.score(X, y)
y_pred = lm.predict(X)
print metrics.mean_squared_error(y, y_pred)

[  0.          50.58862175  -1.88776945   2.59269572   0.        ]
1.87681467246


In [19]:
lm = linear_model.ElasticNet(alpha=0.2, l1_ratio=0.5)
lm.fit(X, y)
print lm.coef_
# print "R^2", lm.score(X, y)
y_pred = lm.predict(X)
print metrics.mean_squared_error(y, y_pred)

[  0.13976379  21.9356334   -2.41193537   2.73535287  21.93243228]
19.4195629434
